### ISSUE TITLE
EMS 국제등기에대한 지원을 하지 않습니다

### ISSUE THREAD

**Issue by LanaKee** [kimain050401/DTS#1]
EMS국제특급등기의경우 운송장번호 앞자리에 알파뱃이 붙으나 input창은 number만 지원하여 사실상 사용할수 없게되어있습니다

**Comment by kimain050401** [comment]
EMS의 경우, 국내 EMS가 아닌 미국의 EMS를 지원합니다.
국내 우체국 EMS는 API 단에서 지원하지 않고 있음을 알려드립니다 :)

**Comment by kimain050401** [comment]
답변 후 일주일이 지나 이슈 닫겠습니다! 감사합니다 :)
